# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. 
on:
  push:
  pull_request:
    types: [ opened, synchronize, edited ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  wow_thats_big:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use wow-thats-big
        uses: ./
        with:
          root_directory: test
        env:
          MIN_CYCLOMATIC_COMPLEXITY: 5.0
          MIN_FILE_SIZE_KB: 512
